<h2>Curving Test Grades</h2>


In [183]:
import numpy as np
CURVE_CENTER = 80


def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)

In [184]:

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

<h2>Array Shapes and Axes</h2>


Creating numpy array and reshaping it into 3 planes of 3 rows x 2 cols


In [185]:
temperatures = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 22.2,
    13.6, 46.4, 32.6, 11.3, 93.2, 25.2
]).reshape(3, 3, 2)

In [186]:
print(temperatures.shape)

(3, 3, 2)


In [187]:
print(temperatures)

[[[29.3 42.1]
  [18.8 16.1]
  [38.  12.5]]

 [[12.6 49.9]
  [38.6 31.3]
  [ 9.2 22.2]]

 [[13.6 46.4]
  [32.6 11.3]
  [93.2 25.2]]]


In [188]:
np.swapaxes(temperatures, 1, 2)

array([[[29.3, 18.8, 38. ],
        [42.1, 16.1, 12.5]],

       [[12.6, 38.6,  9.2],
        [49.9, 31.3, 22.2]],

       [[13.6, 32.6, 93.2],
        [46.4, 11.3, 25.2]]])

In [189]:
temperatures.max(axis=2)

array([[42.1, 18.8, 38. ],
       [49.9, 38.6, 22.2],
       [46.4, 32.6, 93.2]])

In [190]:
table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7, 9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
    [1, 3, 5, 9]
])

In [191]:
table.max()

9

In [192]:
table.max(axis=0)

array([5, 6, 7, 9])

In [193]:
table.max(axis=1)

array([7, 9, 1, 4, 9])

<h2>Broadcasting</h2>


In [194]:
A = np.arange(32).reshape(4, 1, 8)
print(np.ndim(A))

3


In [195]:
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [196]:
B = np.arange(48).reshape(1, 6, 8)

In [197]:
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [198]:
B

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [199]:
print(A.shape)
print(B.shape)

(4, 1, 8)
(1, 6, 8)


In [200]:
A+B

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

<h2>Data Science Operations</h2>


<h3>Indexing</h3>


In [201]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

In [202]:
for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34

In [203]:
assert square[:2, :2].sum() == 34

In [204]:
assert square[2:, :2].sum() == 34

In [205]:
assert square[:2, 2:].sum() == 34

In [206]:
square

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [207]:
square[:3, 2:]

array([[ 2, 13],
       [11,  8],
       [ 7, 12]])

In [208]:
square[2:, :2]

array([[ 9,  6],
       [ 4, 15]])

In [209]:
square_2 = np.array([
    [16, 3, 2, 13, 10],
    [5, 10, 11, 8, 19],
    [9, 6, 7, 12, 17],
    [4, 15, 14, 1, 74]
])

In [210]:
print(square_2[1:3, 1:4])

[[10 11  8]
 [ 6  7 12]]


In [211]:
print(square_2[2:, 2:4])

[[ 7 12]
 [14  1]]


<h3>Masking and Filtering</h3>


In [212]:
numbers = np.linspace(6, 54, 24, dtype=int).reshape(-1, 4)

In [213]:
numbers

array([[ 6,  8, 10, 12],
       [14, 16, 18, 20],
       [22, 24, 26, 28],
       [31, 33, 35, 37],
       [39, 41, 43, 45],
       [47, 49, 51, 54]])

In [214]:
mask = numbers % 6 == 0

In [215]:
mask

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [216]:
multiple_of_6 = numbers[mask]

In [217]:
multiple_of_6

array([ 6, 12, 18, 24, 54])

## Transposing


In [218]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

In [219]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

## Concat


In [220]:
a = np.array([
    [4, 8],
    [6, 1]
])

In [221]:
b = np.array([
    [3, 5],
    [7, 2],
])

In [222]:
np.hstack((a, b))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [223]:
np.vstack((b, a))

array([[3, 5],
       [7, 2],
       [4, 8],
       [6, 1]])

In [224]:
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [225]:
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

## Sort


In [226]:
data = np.array([
    [7, 1, 4],
    [8, 6, 5],
    [1, 2, 3]
])

In [227]:
np.sort(data)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [228]:
np.sort(data, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [229]:
np.sort(data, axis=1)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [230]:
data

array([[7, 1, 4],
       [8, 6, 5],
       [1, 2, 3]])

In [231]:
np.sort(data, axis=0)

array([[1, 1, 3],
       [7, 2, 4],
       [8, 6, 5]])

# Implementation


In [232]:
from math import e, factorial

import numpy as np

fac = np.vectorize(factorial)


def e_x(x, terms=10):
    """Approximates e^x using a given number of terms of
    the Maclaurin series
    """
    n = np.arange(terms)
    return np.sum((x ** n) / fac(n))


if __name__ == "__main__":
    print("Actual:", e ** 3)  # Using e from the standard library

    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")

Actual: 20.085536923187664
N (terms)	Maclaurin	Error
1		1.000		19.086
2		4.000		16.086
3		8.500		11.586
4		13.000		7.086
5		16.375		3.711
6		18.400		1.686
7		19.412		0.673
8		19.846		0.239
9		20.009		0.076
10		20.063		0.022
11		20.080		0.006
12		20.084		0.001
13		20.085		0.000


In [233]:
import concurrent.futures
from threading import Lock


class Foo:
    def __init__(self):
        self.locks = (Lock(), Lock())
        self.locks[0].acquire()
        self.locks[1].acquire()

    def first(self, printFirst: 'Callable[[], None]') -> None:
        # printFirst() outputs "first". Do not change or remove this line.
        printFirst()
        self.locks[0].release()

    def second(self, printSecond: 'Callable[[], None]') -> None:
        with self.locks[0]:
            # printFirst() outputs "first". Do not change or remove this line.
            printSecond()
            self.locks[1].release()
        # printSecond() outputs "second". Do not change or remove this line.

    def third(self, printThird: 'Callable[[], None]') -> None:
        with self.locks[1]:
            # printThird() outputs "third". Do not change or remove this line.
            printThird()


num = [1, 2, 3]
with concurrent.futures.ThreadPoolExecutor(max_workers=None) as Executor:
    thread_1 = Executor.map()

TypeError: Executor.map() missing 1 required positional argument: 'fn'

In [234]:
from threading import Lock
from concurrent.futures import ThreadPoolExecutor


class FooBar:
    def __init__(self, n):
        self.n = n
        self.locks = (Lock(), Lock(), Lock())
        self.locks[0].acquire()
        self.locks[1].acquire()

    def foo(self) -> None:
        for i in range(self.n):
            with self.locks[2]:
                # printFoo() outputs "foo". Do not change or remove this line.
                print("Foo")
                self.locks[0].release()

    def bar(self) -> None:
        for i in range(self.n):
            with self.locks[0]:
                # printBar() outputs "bar". Do not change or remove this line.
                self.locks[0].acquire()
                with self.locks[2]:
                    print("Bar")
                    self.locks[1].release()


object_foo_bar = FooBar(3)
with ThreadPoolExecutor(max_workers=None) as Executor:
    thread_foo = Executor.submit(FooBar.foo(object_foo_bar))
    thread_bar = Executor.submit(FooBar.bar(object_foo_bar))

Foo
Foo


RuntimeError: release unlocked lock

In [236]:
from threading import Lock
from threading import Barrier
from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor

class FooBar:
    def __init__(self, n):
        self.n = n
        self.locks = (Lock(), Lock(), Lock())
        self.locks[0].acquire()
        self.locks[1].acquire()
        self.barrier = Barrier(2)

    def foo(self) -> None:
        for i in range(self.n):
            print("Foo")
            self.barrier.wait()

    def bar(self) -> None:
        for i in range(self.n):
            print("Bar")
            self.barrier.wait()


object_foo_bar = FooBar(3)

with ThreadPoolExecutor(max_workers=None) as executor:
    thread_foo = executor.submit(object_foo_bar.foo)
    thread_bar = executor.submit(object_foo_bar.bar)

# Wait for threads to finish
thread_foo.result()
thread_bar.result()

Foo
Bar
Bar
Foo
Bar
Foo


In [237]:
import numpy as np
list_num = np.array([2, 4, 8])

In [238]:
print(list_num)

[2 4 8]


In [240]:
import numpy as np

N, M = list(map(int, input().split()))

print(N, M)

2 2


In [242]:
import numpy as np

N, M = list(map(int, input().split()))


array_np = np.array([input().split() for _ in range(N)], dtype=int)

print(array_np.T)
print(array_np.flatten())

[[1 3]
 [2 4]]
[1 2 3 4]


In [243]:
import numpy as np
data = np.array([
    ("joe", 32, 6),
    ("mary", 15, 20),
    ("felipe", 80, 100),
    ("beyonce", 38, 9001),
], dtype=[("name", str, 10), ("age", int), ("power", int)])

In [244]:
data[0]

('joe', 32, 6)

In [245]:
data[data['age'] > 35]['name']

array(['felipe', 'beyonce'], dtype='<U10')

## Hacker Rank Practice Questions

In [246]:
import numpy as np

N, M, P = list(map(int, (input().split())))

zero_array = np.zeros((N, M, P), int)
ones_array = np.ones((N, M, P), int)

print(zero_array)
print(ones_array)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [247]:
import numpy as np

def create_array(func_for,*args):
    size=len(args)
    list_dim=[x for x in args]
    if func_for==0:
        zero_array = np.zeros((list_dim), dtype=int)
        return zero_array
    else:
        ones_array=np.ones((list_dim), dtype=int)
        return ones_array

user_input = input()
user_values = list(map(int, user_input.split()))

zero_array = create_array(0,*user_values)
ones_array = create_array(1,*user_values)
print(zero_array)
print(ones_array)


[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [248]:
import numpy as np

N, M=list(map(int,input().split()))

identity_matrix=np.eye(N,M)
print(identity_matrix)

[[1. 0.]
 [0. 1.]]


Input Format

The first line contains two space separated integers,N  and M.
The next N lines contains M space separated integers of array.
The following  lines contains M space separated integers of array.

In [ ]:
import numpy as np

def read_array(N, M):
    array_=np.zeros(shape=(N,M),dtype=int)
    for x in range(N):
        row=list(map(int,input().split()))
        array_[x]=row
    return array_

N, M = list(map(int,input().split()))
array_A=read_array(N, M)
array_B=read_array(N, M)

In [ ]:
array_A

In [ ]:
array_B

In [ ]:
print(array_A+array_B)
print(array_A-array_B)
print(array_A*array_B)
print(array_A//array_B)
print(array_A%array_B)
print(array_A**array_B)

In [ ]:
import numpy as np
input_=list(input().split())
input_=[float(x) for x in input_]

In [ ]:
print(np.floor(input_))
print(np.ceil(input_))
print(np.rint(input_))

In [ ]:
_

In [ ]:
import numpy as np

def prod_(my_array, axis_=0):
    product=np.prod(my_array,axis=axis_)
    print(product)


def sum_(array_, axis_=None):
    sum=np.sum(array_,axis=axis_)
    print(sum)


def read_array(row_, col_):
    array_=np.zeros(shape=(row_,col_),dtype=int)
    for x in range(N):
        new_row=list(map(int,input().split()))
        array_[x]=new_row
    return array_

N, M = list(map(int,input().split()))
array_x=read_array(N,M)
prod_(array_x,1)
sum_(array_x,1)

In [ ]:
def sum_(array_, axis_=None):
    sum=np.sum(array_,axis=axis_)
    print(sum)
sum_(array_x,1)

In [ ]:
def prod_(my_array, axis_=0):
    product=np.prod(my_array,axis=axis_)
    print(product)
prod_(array_x,1)

In [ ]:
array_x

In [ ]:
import numpy as np
def read_array(row_, col_):
    array_=np.zeros(shape=(row_,col_),dtype=int)
    for x in range(N):
        new_row=list(map(int,input().split()))
        array_[x]=new_row
    return array_

In [ ]:
N, M = list(map(int,input().split()))
array_x=read_array(N,M)
print(array_x)

In [ ]:
min=np.min(array_x,axis=1)
print(min)

In [ ]:
max=np.max(min)

In [ ]:
max

In [ ]:
import numpy as np
def read_array(row_, col_):
    array_=np.zeros(shape=(row_, col_), dtype=int)
    for x in range(N):
        new_row=list(map(int, input().split()))
        array_[x]=new_row
    return array_
    
N, M = list(map(int, input().split()))
array_z=read_array(N, M)

In [ ]:
def format_float(value):
    # Format the float with up to 11 decimal places, removing trailing zeros
    formatted_value = '{:.11f}'.format(value).rstrip('0').rstrip('.')
    return formatted_value

In [ ]:
mean=np.mean(array_z,axis=1)
var=np.var(array_z,axis=0)
std=np.std(array_z,axis=None)
std = format_float(std)

In [ ]:
print(f"{mean}\n{var}\n{np.std(array_z,axis=None)}")

In [2]:
import numpy as np
import re
def read_array(row_, col_):
    array_=np.zeros(shape=(row_, col_), dtype=int)
    for x in range(N):
        new_row=list(map(int, input().split()))
        array_[x]=new_row
    return array_
    
def format_float(value):
    formatted_value = '{:.11f}'.format(value).rstrip('0')
    return formatted_value
N, M = list(map(int, input().split()))
array_z=read_array(N, M)
patern=r"\d.$"
mean=np.mean(array_z, axis=1)
var=np.var(array_z, axis=0)
std=np.std(array_z, axis=None)
std = format_float(std)

print(f"{mean}\n{var}\n{std}")

[1.5 3.5]
[1. 1.]
1.11803398875


In [5]:
mean=np.mean(array_z, axis=0)
var=np.var(array_z, axis=1)
std=np.std(array_z, axis=None)
std = format_float(std)
print(f"{mean}\n{var}\n{std}")

[2. 3.]
[0.25 0.25]
1.11803398875


In [3]:
array_z

array([[1, 2],
       [3, 4]])

## Vectorization Advance

### creating numpy array with high and low and also the number of integers

In [ ]:
import numpy as np
prices = np.random.uniform(low=50,high=60,size=(3,5,10,5))

In [ ]:
prices=prices.astype(int)
print(prices)

In [ ]:
random_from_array=np.random.choice(prices[1][1])

In [ ]:
prices[1][1][0]

In [ ]:
prices = np.full(100, fill_value=np.nan)

In [ ]:
prices[[0,24,49,74,99]]=(99,55,15,5,33)

In [ ]:
prices

In [ ]:
x = np.arange(len(prices))

In [ ]:
x

In [ ]:
is_valid = ~np.isnan(prices)

In [ ]:
is_valid

In [ ]:
prices = np.interp(x=x, xp=x[is_valid], fp=prices[is_valid])

In [ ]:
prices

In [ ]:
prices += np.random.randn(len(prices)) * 2

In [ ]:
prices

## NumPy Interpolation

In [ ]:
import numpy as np

day = np.array([2, 4, 7])
gold_price = np.array([55, 58, 65])

# find the value of gold on day 3
day3_value = np.interp(6, day, gold_price)

print("The value of gold on day 3 is", day3_value)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# arrays with random data points
x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 3, 4, 5, 7, 8]) 

# generate evenly spaced values between the minimum and maximum x values
x_interp = np.linspace(x.min(), x.max(), 100)

# interp() to interpolate y values
y_interp = np.interp(x_interp, x, y)

# plot the original data points and the interpolated values
plt.plot(x, y, 'bo')
plt.plot(x_interp, y_interp, 'r-')

plt.show()

In [ ]:
x_interp

In [ ]:
y_interp

In [ ]:
from numpy import random
result = random.randint(0, 10, (3,4))

In [348]:
import numpy as np
import time

rng = np.random.default_rng()

Random Integer: 4
Random Float: 0.7607231957142276
Array of Random Floats: [0.22277366 0.63071792 0.91578732 0.81070365 0.46754775]
Random Normal Distribution: [-2.21189607  0.8388492   1.24006767  0.1597465   0.03448624]
Random Choice: [2 3 2 3 1]
Shuffled Array: [3 8 2 9 6 0 4 1 7 5]
Permuted Array: [3 4 2 6 0 8 9 5 1 7]


In [486]:
# Generating random integers
random_int = rng.integers(0, 10)  # Random integer between 0 (inclusive) and 10 (exclusive)
print("Random Integer:", random_int)

Random Integer: 4


In [487]:
# Generating random floats
random_float = rng.random()  # Random float between 0 (inclusive) and 1 (exclusive)
print("Random Float:", random_float)

Random Float: 0.9500478914702405


In [491]:
# Generating an array of random floats
random_floats = rng.random(size=5)  # Array of 5 random floats
print("Array of Random Floats:", random_floats)

Array of Random Floats: [0.94319112 0.17867053 0.79424955 0.69858549 0.08024261]


In [493]:
# Generating random floats from a normal distribution
random_normal = rng.normal(2, 5, size=5)  # Random floats from a normal distribution with mean 0 and standard deviation 1
print("Random Normal Distribution:", random_normal)

Random Normal Distribution: [-6.68646695 -1.54867124  3.72619394  1.24638511 10.70055206]


In [495]:
# Generating random integers with specified probabilities
random_choice = rng.choice([1, 2, 3,4,7], size=50, p=[.50,.20,.10,.10,.10])  # Randomly choose from the given values with specified probabilities
print("Random Choice:", random_choice)

Random Choice: [2 3 4 1 4 2 3 2 2 2 1 1 2 1 7 4 2 1 2 1 1 7 1 3 1 1 1 1 1 2 3 1 3 4 3 1 4
 1 1 1 2 1 7 4 1 1 1 1 1 1]


In [462]:
# Shuffling an array
arr = np.arange(10)
print("Shuffled Array:", arr)
rng.shuffle(arr)  # In-place shuffle
print("Shuffled Array:", arr)

Shuffled Array: [0 1 2 3 4 5 6 7 8 9]
Shuffled Array: [6 0 8 2 9 7 4 1 3 5]


In [1]:
# Permuting an array
print("Array:", arr)
permuted_arr = rng.permutation(arr)  # Returns a new permuted array
print("Permuted Array:", permuted_arr)

NameError: name 'arr' is not defined

In [463]:
import numpy as np

nrandom=np.random.default_rng(1)

In [ ]:
nrandom.uniform(low=10,high=100,size=10).astype(int)

In [13]:
import numpy as np
rng=np.random.default_rng()
arr = np.arange(10)
print("Shuffled Array:", arr)
rng.shuffle(arr)  # In-place shuffle
print("Shuffled Array:", arr)
data_types = np.ufunc.types

Shuffled Array: [0 1 2 3 4 5 6 7 8 9]
Shuffled Array: [8 7 9 4 5 3 1 6 2 0]


In [14]:
data_types

<attribute 'types' of 'numpy.ufunc' objects>

In [15]:
ufunc_types = np.add.types
print(ufunc_types)

['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'Mm->M', 'mm->m', 'mM->M', 'OO->O']


Original arrays:
[[1 2]
 [3 4]
 [5 6]]
[7 8]
Dot product of the said two arrays:
[23 53 83]
Explanation:

In the above exercise -

nums1 = np.array([[1, 2], [3, 4], [5, 6]]): This code creates a 2D NumPy array with shape (3, 2) containing 
the values [[1, 2], [3, 4], [5, 6]] and assigns it to the variable nums1.

nums2 = np.array([7, 8]): This code creates a 1D NumPy array with shape (2,) containing the values [7, 8] and 
assigns it to the variable nums2.

result = np.dot(nums1, nums2): Here dot() function performs dot product between nums1 and nums2, and 
assigns the result to the variable result. Since nums1 has shape (3, 2) and nums2 has shape (2,), the dot product 
results in a 1D array with shape (3,) containing the values [23, 53, 83].

## NumPy Advance

### Question 01
Write a NumPy program to find the dot product of two arrays of different dimensions.

In [66]:
array_1=np.array([1,2,3,4,5,6]).reshape(3,2)
print(array_1)
array_2=np.array([7,8]).reshape(2,)
array_2.reshape(2,1)
print(array_2)
result=np.dot(array_1,array_2)

[[1 2]
 [3 4]
 [5 6]]
[7 8]


In [65]:
result

array([23, 53, 83])

### Question 02
Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.

In [81]:
matrix_iden=np.identity(3).astype(int)
matrix_iden_vertically_stack=np.vstack([matrix_iden,matrix_iden,matrix_iden])
matrix_iden_horizantally_stack=np.hstack([matrix_iden,matrix_iden,matrix_iden])

print(matrix_iden)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [79]:
matrix_iden_vertically_stack

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [82]:
matrix_iden_horizantally_stack

array([[1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1]])

### Question 3
Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [88]:
rng=np.random.default_rng()
four_x_array=rng.uniform(low=1,high=20,size=(4,4)).astype(int)

In [89]:
four_x_array

array([[ 5,  3, 14,  4],
       [ 2, 11,  8, 10],
       [ 2,  4,  4, 18],
       [10, 16, 16, 13]])

In [92]:
row_sum=np.sum(four_x_array,axis=1)

In [93]:
row_sum

array([26, 31, 28, 55])

### Question 4
Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.

In [96]:
import numpy as np
rng=np.random.default_rng()
array_q4=rng.uniform(low=1,high=50,size=(3,3)).astype(int)


In [99]:
mean_array_row=np.mean(array_q4,axis=1).astype(int)
print(mean_array_row)

[18 28 18]


In [101]:
modified_array=np.subtract(array_q4,mean_array_row)

In [102]:
modified_array

array([[ -1,  -9,   2],
       [ 23,  12, -15],
       [  2, -24,  13]])

In [103]:
array_q4

array([[17, 19, 20],
       [41, 40,  3],
       [20,  4, 31]])

### Question 5
Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.

In [104]:
import numpy as np
rng=np.random.default_rng()
array_q4=rng.uniform(low=1,high=50,size=(3,3)).astype(int)

In [105]:
mean_array_row=np.mean(array_q4,axis=0).astype(int)
print(mean_array_row)

[10 29 14]


In [106]:
modified_array=np.subtract(array_q4,mean_array_row)

In [107]:
modified_array

array([[ -1, -19, -13],
       [ 10,  17,  12],
       [ -7,   3,   2]])

In [108]:
array_q4

array([[ 9, 10,  1],
       [20, 46, 26],
       [ 3, 32, 16]])

### Question 6
Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.

In [122]:
import numpy as np
nums = np.random.uniform(low=1, high=5, size=(2,2,2,2)).astype(int)
print("Original array elements:")
print(nums)
sum_along_last_axis = np.sum(nums, axis=-1).astype(int)
print("\nSum along the last axis:")
print(sum_along_last_axis)

Original array elements:
[[[[1 3]
   [2 3]]

  [[2 2]
   [1 2]]]


 [[[4 3]
   [4 3]]

  [[4 1]
   [1 2]]]]

Sum along the last axis:
[[[4 5]
  [4 3]]

 [[7 7]
  [5 3]]]


### Question 11
Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.

In [125]:
import numpy as np
nums = np.random.uniform(low=1, high=50, size=(5,5)).astype(int)
print("Original array elements:")
print(nums)

Original array elements:
[[45 34 47 39 42]
 [34 37  8 39 13]
 [12 29 34 38 10]
 [30 23 42 45 11]
 [22 48 11  3 32]]


In [211]:
max_each_row=np.max(nums,axis=1)
sorted_max=np.sort(nums,axis=1)
sorted_max=sorted_max.T
second_max_each_row=sorted_max[3:2:-1]
print(max_each_row)
print(second_max_each_row.flatten())

[47 39 38 45 48]
[45 37 34 42 32]


In [225]:
second_largest_m = np.partition(nums, -2, axis=1)

In [226]:
second_largest_a = np.partition(nums, 1, axis=1)

In [227]:
second_largest_m

array([[39, 42, 34, 45, 47],
       [ 8, 13, 34, 37, 39],
       [10, 12, 29, 34, 38],
       [23, 11, 30, 42, 45],
       [ 3, 11, 22, 32, 48]])

In [228]:
second_largest_a

array([[34, 39, 47, 45, 42],
       [ 8, 13, 34, 39, 37],
       [10, 12, 34, 38, 29],
       [11, 23, 42, 45, 30],
       [ 3, 11, 48, 22, 32]])

In [229]:
arr = np.array([5, 4, 1, 0, -1, -3, -4, 0])

In [335]:
arr = np.random.uniform(low=1, high=50, size=(1,10)).astype(int)


[[29 25 41 14 42 35 17 35 44  8]]


array([[25,  8, 17, 14, 29, 35, 35, 41, 44, 42]])

In [353]:
arr=rng.integers(0,30,20)
np.partition(arr,5)

array([ 4,  6,  0,  6,  7,  8,  8, 11, 12, 12, 14, 16, 12, 25, 23, 20, 26,
       16, 27, 19], dtype=int64)

In [354]:
np.partition(arr,4)

array([ 4,  6,  0,  6,  7,  8,  8, 11, 12, 12, 14, 16, 12, 25, 23, 20, 26,
       16, 27, 19], dtype=int64)

In [355]:
arr=rng.integers(0,30,(5,5))

In [356]:
arr

array([[21, 11,  4, 16, 18],
       [ 4, 13, 24,  5,  8],
       [26,  8, 21, 18,  3],
       [21, 17,  1, 26, 20],
       [12, 10, 16, 18, 13]], dtype=int64)

In [362]:
index_row,index_col=list(map(int,input("Enter Row and Col Index Space Seperated").split()))

print(arr[index_row][index_col])



26


In [367]:
value_to_replace=int(input("Enter Replace value"))
print(value_to_replace)
arr[index_row+1][index_col]=[[value_to_replace]]
arr[index_row][index_col+1]=[value_to_replace]
arr[index_row-1][index_col]=[value_to_replace]
arr[index_row][index_col-1]=[value_to_replace]
arr[index_row+1][index_col+1]=[value_to_replace]
arr[index_row-1][index_col-1]=[value_to_replace]
arr[index_row-1][index_col+1]=[value_to_replace]
arr[index_row-1][index_col+1]=[value_to_replace]


TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'