<h2>Curving Test Grades</h2>


In [250]:
import numpy as np
CURVE_CENTER = 80


def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)

In [251]:

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

<h2>Array Shapes and Axes</h2>


Creating numpy array and reshaping it into 3 planes of 3 rows x 2 cols


In [252]:
temperatures = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 22.2,
    13.6, 46.4, 32.6, 11.3, 93.2, 25.2
]).reshape(3, 3, 2)

In [253]:
print(temperatures.shape)

(3, 3, 2)


In [254]:
print(temperatures)

[[[29.3 42.1]
  [18.8 16.1]
  [38.  12.5]]

 [[12.6 49.9]
  [38.6 31.3]
  [ 9.2 22.2]]

 [[13.6 46.4]
  [32.6 11.3]
  [93.2 25.2]]]


In [255]:
np.swapaxes(temperatures, 1, 2)

array([[[29.3, 18.8, 38. ],
        [42.1, 16.1, 12.5]],

       [[12.6, 38.6,  9.2],
        [49.9, 31.3, 22.2]],

       [[13.6, 32.6, 93.2],
        [46.4, 11.3, 25.2]]])

In [256]:
temperatures.max(axis=2)

array([[42.1, 18.8, 38. ],
       [49.9, 38.6, 22.2],
       [46.4, 32.6, 93.2]])

In [257]:
table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7, 9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
    [1, 3, 5, 9]
])

In [258]:
table.max()

9

In [259]:
table.max(axis=0)

array([5, 6, 7, 9])

In [260]:
table.max(axis=1)

array([7, 9, 1, 4, 9])

<h2>Broadcasting</h2>


In [261]:
A = np.arange(32).reshape(4, 1, 8)
print(np.ndim(A))

3


In [262]:
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [263]:
B = np.arange(48).reshape(1, 6, 8)

In [264]:
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [265]:
B

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [266]:
print(A.shape)
print(B.shape)

(4, 1, 8)
(1, 6, 8)


In [267]:
A+B

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

<h2>Data Science Operations</h2>


<h3>Indexing</h3>


In [268]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

In [269]:
for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34

In [270]:
assert square[:2, :2].sum() == 34

In [271]:
assert square[2:, :2].sum() == 34

In [272]:
assert square[:2, 2:].sum() == 34

In [273]:
square

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [274]:
square[:3, 2:]

array([[ 2, 13],
       [11,  8],
       [ 7, 12]])

In [275]:
square[2:, :2]

array([[ 9,  6],
       [ 4, 15]])

In [276]:
square_2 = np.array([
    [16, 3, 2, 13, 10],
    [5, 10, 11, 8, 19],
    [9, 6, 7, 12, 17],
    [4, 15, 14, 1, 74]
])

In [277]:
print(square_2[1:3, 1:4])

[[10 11  8]
 [ 6  7 12]]


In [278]:
print(square_2[2:, 2:4])

[[ 7 12]
 [14  1]]


<h3>Masking and Filtering</h3>


In [279]:
numbers = np.linspace(6, 54, 24, dtype=int).reshape(-1, 4)

In [280]:
numbers

array([[ 6,  8, 10, 12],
       [14, 16, 18, 20],
       [22, 24, 26, 28],
       [31, 33, 35, 37],
       [39, 41, 43, 45],
       [47, 49, 51, 54]])

In [281]:
mask = numbers % 6 == 0

In [282]:
mask

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [284]:
multiple_of_6 = numbers[mask]

In [285]:
multiple_of_6

array([ 6, 12, 18, 24, 54])

## Transposing


In [286]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

In [287]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

## Concat


In [289]:
a = np.array([
    [4, 8],
    [6, 1]
])

In [288]:
b = np.array([
    [3, 5],
    [7, 2],
])

In [290]:
np.hstack((a, b))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [291]:
np.vstack((b, a))

array([[3, 5],
       [7, 2],
       [4, 8],
       [6, 1]])

In [292]:
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [293]:
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

## Sort


In [294]:
data = np.array([
    [7, 1, 4],
    [8, 6, 5],
    [1, 2, 3]
])

In [295]:
np.sort(data)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [296]:
np.sort(data, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [301]:
np.sort(data, axis=1)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [298]:
data

array([[7, 1, 4],
       [8, 6, 5],
       [1, 2, 3]])

In [303]:
np.sort(data, axis=0)

array([[1, 1, 3],
       [7, 2, 4],
       [8, 6, 5]])

# Implementation


In [304]:
from math import e, factorial

import numpy as np

fac = np.vectorize(factorial)


def e_x(x, terms=10):
    """Approximates e^x using a given number of terms of
    the Maclaurin series
    """
    n = np.arange(terms)
    return np.sum((x ** n) / fac(n))


if __name__ == "__main__":
    print("Actual:", e ** 3)  # Using e from the standard library

    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")

Actual: 20.085536923187664
N (terms)	Maclaurin	Error
1		1.000		19.086
2		4.000		16.086
3		8.500		11.586
4		13.000		7.086
5		16.375		3.711
6		18.400		1.686
7		19.412		0.673
8		19.846		0.239
9		20.009		0.076
10		20.063		0.022
11		20.080		0.006
12		20.084		0.001
13		20.085		0.000


In [311]:
import concurrent.futures
from threading import Lock


class Foo:
    def __init__(self):
        self.locks = (Lock(), Lock())
        self.locks[0].acquire()
        self.locks[1].acquire()

    def first(self, printFirst: 'Callable[[], None]') -> None:
        # printFirst() outputs "first". Do not change or remove this line.
        printFirst()
        self.locks[0].release()

    def second(self, printSecond: 'Callable[[], None]') -> None:
        with self.locks[0]:
            # printFirst() outputs "first". Do not change or remove this line.
            printSecond()
            self.locks[1].release()
        # printSecond() outputs "second". Do not change or remove this line.

    def third(self, printThird: 'Callable[[], None]') -> None:
        with self.locks[1]:
            # printThird() outputs "third". Do not change or remove this line.
            printThird()


num = [1, 2, 3]
with concurrent.futures.ThreadPoolExecutor(max_workers=None) as Executor:
    thread_1 = Executor.map()

In [ ]:
from threading import Lock
from concurrent.futures import ThreadPoolExecutor
class FooBar:
    def __init__(self, n):
        self.n = n
        self.locks=(Lock(),Lock(),Lock())
        self.locks[0].acquire()
        self.locks[1].acquire()



    def foo(self) -> None:
        for i in range(self.n):
            with self.locks[2]:
            # printFoo() outputs "foo". Do not change or remove this line.
                print("Foo")
                self.locks[0].release()



    def bar(self) -> None:
        for i in range(self.n):
            with self.locks[0]:
            # printBar() outputs "bar". Do not change or remove this line.
                self.locks[0].acquire()
                with self.locks[2]:
                    print("Bar")
                    self.locks[1].release()

object_foo_bar=FooBar(3)
with ThreadPoolExecutor(max_workers=None) as Executor:
    thread_foo=Executor.submit(FooBar.foo(object_foo_bar))
    thread_bar=Executor.submit(FooBar.bar(object_foo_bar))

In [2]:
from threading import Lock
from threading import Barrier
from concurrent.futures import ThreadPoolExecutor

class FooBar:
    def __init__(self, n):
        self.n = n
        self.locks = (Lock(), Lock(), Lock())
        self.locks[0].acquire()
        self.locks[1].acquire()
        self.barrier=Barrier(2)

    def foo(self) -> None:
        for i in range(self.n):
            print("Foo")
            self.barrier.wait()

    def bar(self) -> None:
        for i in range(self.n):
            print("Bar")
            self.barrier.wait()

object_foo_bar = FooBar(3)

with ThreadPoolExecutor(max_workers=None) as executor:
    thread_foo = executor.submit(object_foo_bar.foo)
    thread_bar = executor.submit(object_foo_bar.bar)

# Wait for threads to finish
thread_foo.result()
thread_bar.result()


Foo
Bar
Bar
Foo
Bar
Foo


In [33]:
import numpy as np
list_num=np.array([2,4,8])

In [36]:
print(list_num)
    


14


In [3]:
import numpy as np

N, M = list(map(int, input().split()))

print(N, M)

In [ ]:
import numpy as np

N, M = list(map(int, input().split()))


array_np=np.array([input().split() for _ in range(N)], dtype=int)

print(array_np.T)
print(array_np.flatten())

In [2]:
import numpy as np
data = np.array([
    ("joe", 32, 6),
    ("mary", 15, 20),
    ("felipe", 80, 100),
    ("beyonce", 38, 9001),
], dtype=[("name", str, 10), ("age", int), ("power", int)])

In [3]:
data[0]

('joe', 32, 6)